### ISSUE TITLE
Some plugins fail to download since they no longer support Scala 2.10

### ISSUE THREAD

**Issue by toxicafunk** [radanalyticsio/oshinko-s2i#293]
On project/plugins.sbt:

`addCompilerPlugin("com.olegpy" %% "better-monadic-for" % "0.3.0")`

The above fails because better-monadic-for no longer as a "better-monadic-for_2.10" version.

This can be fixed specifying the version:

`addCompilerPlugin("com.olegpy" % "better-monadic-for_2.11" % "0.3.0")`

but it creates a problem if on you local machine you have scala 2.12:

`java.lang.NoClassDefFoundError: scala/tools/nsc/transform/Transform$class`

Maybe its time to update the scala and sbt versions of the base image since more plugins/libraries are dropping 2.10 support, i.e. sbt-wartremover and sbt-scalafmt,

**Comment by elmiko** [comment]
thanks for reporting this, i am going to ping a few of our scala experts.

@erikerlandson @willb any thoughts about this?

**Comment by toxicafunk** [comment]
Hi @elmiko,

Thanks for your prompt response. It looks like radanalyticsio/s2i-scala-container is [already prepared to run 2.11.8](radanalyticsio/s2i-scala-container). So I will focus on `module/scala` to see why its not being used.

**Comment by elmiko** [comment]
it all starts here

https://github.com/radanalyticsio/oshinko-s2i/blob/master/image.scala.yaml#L6

but perhaps there is some issue where we are not building a proper image from the 2.11 stuff in that repo. i'm not sure

**Comment by toxicafunk** [comment]
The issue seems to be related with using sbt 0.13 which downloads scala 2.10 , upgrading to sbt 1.2x seems to fix the problem:

Using sbt 0.13
`Getting Scala 2.10.6 (for sbt)...`

Using 1.2.1
`Getting Scala 2.11.6 (for sbt)...`

Not sure the proper way to address this in a PR.

I'm currently working on a PR for using spark 2.4.4 with Scala 2.12 and Hadoop 2.8.5 though.

**Comment by tmckayus** [comment]
hmm, I may have just run into this in a PR build. I'll give it a try

**Comment by toxicafunk** [comment]
Here's the PR as promised: https://github.com/radanalyticsio/oshinko-s2i/pull/298
